### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by zzkkzz** [amazon-science/unconditional-time-series-diffusion#3]
In bin/train_model.py 214, the setting of pl.Trainer(). Maybe  "devices=1" should be modified to something like "devices=[int(config["device"][-1])]" to set the right gpu ids

**Comment by abdulfatir** [comment]
> In bin/train_model.py 214, the setting of pl.Trainer(). Maybe "devices=1" should be modified to something like "devices=[int(config["device"][-1])]" to set the right gpu ids

You're right. We always tested on a machine with a single GPU, so this got overlooked. Thanks!

> Did I make some mistakes in setting ? This problem occurs when epochs reach around 49, so I think there may be something wrong with sampling.

I am actually not sure about this. I did not face such an issue. Do you have a MWE by any chance? If not, I will try to start a training job on my end. 

cc @marcelkollovieh

**Comment by abdulfatir** [comment]
@zzkkzz can you share the exact command/config that you're running?

**Comment by abdulfatir** [comment]
I ran this job and it works for me.
```
python bin/train_model.py -c configs/train_tsdiff/train_solar.yaml
```
Output:
```
Epoch 445/999 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95/-- 0:00:04 • -:--:-- 22.72it/s
```

**Comment by zzkkzz** [comment]
Thank you for your reply! My second problem is about pytorch1.13.1 and anaconda environment, I solved this problem by installing pytorch1.12.1 separately. This problem is beacause installing pytorch1.13.1 will automatically download nvidia_cublas_cu11,nvidia_cuda_nvrtc_cu11,nvidia_cuda_runtime_cu11 and nvidia_cudnn_cu11 which will lead to some conflicts about cuda toolkit. So installing pytorch1.12.1 separately when creating the environment can avoid those conflicts. Thank you again for your work!

**Comment by abdulfatir** [comment]
Great! Closing this issue. Please open a new one, if face other problems. :)

**Comment by abdulfatir** [comment]
Reopening to keep track of the GPU ID issue.
