### ISSUE TITLE
Reproduce Figure 3

### ISSUE THREAD

**Issue by hmnza** [amazon-science/unconditional-time-series-diffusion#8]
Hi! How are you?

After resolving various issues that arose during the process of configuring the environment, I basically reproduced the CRPS indicators mentioned in your article by running the commands "Python bin/train_model. py - c configs/train_tsdiff/train_uber_tlc. yaml" and "Python bin/guidance-experience.py - c configs/guidance/guidance_uber_tlc. yaml -- ckpt/path/to/ckpt". However, when I tried to reproduce Figure 3 in the article, which is "Example forecasts generated by TSDiff-Q for time series in Electricity, KDDCup, and Exchange three datasets with different frequencies and/or prediction lengths.", I did not find the corresponding code. What should I do to reproduce that figure?

Thanks!

**Comment by hmnza** [comment]
I have been trying various codes to reproduce Figure 3 in the past few days, but the images I have created are extremely chaotic and have a huge gap from Figure 3. I really have no other choice, what should I do to reproduce Figure 3?

**Comment by abdulfatir** [comment]
Hi! Are you able to reproduce the CRPS numbers? Also, can you please specify what is the exact problem you're facing? Saying "extremely chaotic and have a huge gap" doesn't really help me understand your problem. cc @marcelkollovieh

**Comment by hmnza** [comment]
I successfully obtained the CRPS indicators for the UberTLC dataset by executing the commands "python bin/train_model.py -c configs/train_tsdiff/train_uber_tlc.yaml" and "python bin/guidance_experiment.py -c configs/guidance/guidance_uber_tlc.yaml --ckpt /path/to/ckpt". After that, I wanted to generate a figure similar to Figure 3 in the article, so I attempted to accomplish this task by executing some commands in bin/guidance_experiment.py. I tried several times, and only three of them were successful in generating figures, but all three were far from Figure 3. Below are the commands I used, and the corresponding figures are attached.
FIRST:
        forecasts = list(tqdm(forecast_it, total=len(transformed_testdata)))
        tss = list(ts_it)
        plt.clf()
        for i in range(len(forecasts)):
            forecast_entry = forecasts[i]
            target_entry = tss[i]
            plt.plot(forecast_entry.mean, color='r', label='Forecast')
            plt.plot(target_entry.values, color='b', label='Actual')
            plt.legend()
 SECOND:
         forecasts = list(tqdm(forecast_it, total=len(transformed_testdata)))
         tss = list(ts_it)
         plt.clf()
         for i in range(30):
            forecast_entry = forecasts[i]
            target_entry = tss[i]
            plt.plot(forecast_entry.mean, color='r', label='Forecast')
            plt.plot(target_entry.values, color='b', label='Actual')
            plt.legend()
THIRD:(The corresponding figure here I've deleted from the original and only have a screenshot.)
         forecasts = list(tqdm(forecast_it, total=len(transformed_testdata)))
         tss = list(ts_it)
         plt.clf()
         for i in range(len(forecasts)):
            forecast_entry = forecasts[i]
            target_entry = tss[i]
            plt.plot(forecast_entry.mean[:30], color='r')
            plt.plot(target_entry.values[:30], color='b')
Of course, there are also commands for importing drawing packages, creating canvases, saving drawing files, etc. that I wrote in the rest of bin/guidance_experiment.py, but those have not caused any issues. Not only do I want to make plots similar to Figure 3 on the Uber TLC dataset, but I also want to reproduce Figure 3 on datasets such as Exchange.What should I do to achieve this?
![wt](https://github.com/amazon-science/unconditional-time-series-diffusion/assets/163152889/698f9b24-c745-449f-907c-4a1bd519acb8)
![wt1](https://github.com/amazon-science/unconditional-time-series-diffusion/assets/163152889/bc2dfcc6-2910-4cb5-b32c-001251d84656)
![wt2](https://github.com/amazon-science/unconditional-time-series-diffusion/assets/163152889/ce017fe8-58de-4bb8-ac2d-57277de253da)

**Comment by DennisZZQ** [comment]
@hmnza Hi, do you find how to plot the figure 3?
